services:
  - type: web
    name: trusthire-ai-resume-scanner
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr poppler-utils && \
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.address 0.0.0.0
